common:
    lid_topic:  "/os_cloud_node/points"
    imu_topic:  "/mavros/imu/data_raw"
    time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
    
preprocess:
    lidar_type: 3                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 64
    blind: 0.7

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     150.0
    extrinsic_T: [ 0.111284, -0.123266, 0.038224 ]
    extrinsic_R: [0.999147,  0.019041, -0.036644, -0.017418,  0.998875,  0.044113, 0.037443, -0.043437,  0.998354]

publish:     
    scan_publish_en:  1       # 'false' will close all the point cloud output
    dense_publish_en: 1       # false will low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: 1  # output the point cloud scans in IMU-body-frame